# Generated by Django 4.1.4 on 2022-12-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0002_chatmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='chatID',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='recieverID',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='transmitterID',
            field=models.CharField(max_length=32),
        ),
    ]
