# Generated by Django 4.1.4 on 2022-12-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0003_alter_chatmodel_chatid_alter_chatmodel_recieverid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmodel',
            old_name='datetime',
            new_name='sendingtime',
        ),
    ]
