# Generated by Django 4.1.4 on 2022-12-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0004_rename_datetime_chatmodel_sendingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='chatID',
            field=models.CharField(max_length=64),
        ),
    ]
