# Generated by Django 4.1.4 on 2022-12-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0005_alter_chatmodel_chatid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='chatID',
        ),
    ]
